### PR TITLE
fixed clipboard copying for ios11

### PR DESCRIPTION
**Pull request by albertleao**

### CODE REVIEW

**Comment by AllSeeingEye** [comment]
@albertleao anyway you can tell if the plugin after this change still works on iOS 10?

**Comment by albertleao** [comment]
I'll have to test on xcode. I will try to do that between today and tomorrow.

**Comment by AllSeeingEye** [comment]
Fix still works on iOS 10 - I've tested on a real device.

**Comment by albertleao** [comment]
Awesome. Was going to check after work today. Good stuff :)

**Pull request merged**
